DROP SEQUENCE clientes_codcliente_seq;
CREATE SEQUENCE clientes_codcliente_seq START WITH 1 INCREMENT BY 1 NO MAXVALUE NO MINVALUE CACHE 1;

DROP SEQUENCE dirclientes_id_seq;
CREATE SEQUENCE dirclientes_id_seq START WITH 1 INCREMENT BY 1 NO MAXVALUE NO MINVALUE CACHE 1;

DROP SEQUENCE pedidoscli_idpedido_seq;
CREATE SEQUENCE pedidoscli_idpedido_seq START WITH 1 INCREMENT BY 1 NO MAXVALUE NO MINVALUE CACHE 1;

DROP SEQUENCE lineaspedidoscli_idlinea_seq;
CREATE SEQUENCE lineaspedidoscli_idlinea_seq START WITH 1 INCREMENT BY 1 NO MAXVALUE NO MINVALUE CACHE 1;
